import { faLinkedin } from "@fortawesome/free-brands-svg-icons"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome"
import "./globals.css";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function LoginLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex flex-row gap-1 pt-8 pl-8 ml-2 text-2xl font-bold items-center text-blue-700">
          <h1>Linked</h1>
          <FontAwesomeIcon icon={faLinkedin} className="h-7" />
        </div>
        {children}
        <div className="text-sm text-center mt-8">
          <span>Don&apos;t have an account?</span>
          <button className="text-blue-700 p-1 font-semibold hover:underline hover:rounded-full hover:bg-blue-200">Sign Up</button>
        </div>
      </body>
    </html>
  )
}
